name: flutter_todoapp
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flip: ^2.0.0
  fluent:
    git:
      url: https://github.com/dvc94ch/fluent-dart
      ref: update-intl
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  tlfs: ^0.1.0+9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  msix: ^2.6.7

flutter:
  uses-material-design: true
  assets:
  - assets/todoapp.tlfs.rkyv
  - assets/i18n/en.ftl
  - assets/i18n/de.ftl
