name: flutter_todoapp
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flip: ^2.0.0
  flutter:
    sdk: flutter
  tlfs: ^0.1.0
  tlfs_ios:
    path: packages/tlfs_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/todoapp.tlfs.rkyv
