on:
  push:
    branches:
    - master
  pull_request:

name: flutter-todoapp

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - name: download tlfs
      run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema
    - run: flutter analyze

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: dart format lib --set-exit-if-changed
