on:
  release:
    types:
    - created

name: release flutter-todoapp

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install -y ninja-build libgtk-3-dev
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema todoapp
    - run: flutter config --enable-linux-desktop
    - run: flutter build linux
    - run: linux/appimage/build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: gh release upload $TAG todoapp-x86_64.AppImage
      working-directory: build/appimage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}

  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema todoapp
    - run: flutter build apk
    - run: mv app-release.apk todoapp-aarch64.apk
      working-directory: build/app/outputs/apk/release
    - run: gh release upload $TAG todoapp-aarch64.apk
      working-directory: build/app/outputs/apk/release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema todoapp
    - run: flutter config --enable-macos-desktop
    - run: flutter build macos
    - run: hdiutil create todoapp-uncompressed-x86_64.dmg -ov -volname todoapp -fs HFS+ -srcfolder todoapp.app
      working-directory: build/macos/Build/Products/Release
    - run: hdiutil convert todoapp-uncompressed-x86_64.dmg -format UDZO -o todoapp-x86_64.dmg
      working-directory: build/macos/Build/Products/Release
    - run: gh release upload $TAG todoapp-x86_64.dmg
      working-directory: build/macos/Build/Products/Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}

  ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema todoapp
    - run: flutter build ipa

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema todoapp
    - run: flutter config --enable-windows-desktop
    - run: flutter build windows
    - run: flutter pub run msix:create
    - run: mv flutter_todoapp.msix todoapp-x86_64.msix
      working-directory: build/windows/runner/Release
    - run: gh release upload $TAG todoapp-x86_64.msix
      shell: bash
      working-directory: build/windows/runner/Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}
