on:
  release:
    types:
    - created

name: release flutter-todoapp

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - run: dart run tlfs:download_tlfs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: dart run tlfs:compile_schema
    - run: flutter build apk
    - run: gh release upload $TAG app-release.apk
      working-directory: build/app/outputs/apk/release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}
